name: Build Android App
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar Android Platform 35
        run: |
          yes | sdkmanager "platforms;android-35"

      - name: Setup Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      - name: Download and Unzip Project from Google Drive
        run: |
          pip install gdown
          gdown 1I776Anqd4qPlK_bh2CqdLHzqACQ9q5p0 -O shadows_app.zip
          unzip shadows_app.zip -d app_project

      - name: Forzar API 35 y Corregir Plugin AdMob
        run: |
          cd app_project
          sed -i 's/version="1.0.1"/version="1.0.6"/g' config.xml
          sed -i 's/xmlns:android="http:\/\/schemas.android.com\/apk\/res\/android"/xmlns:android="http:\/\/schemas.android.com\/apk\/res\/android" android-versionCode="10006"/g' config.xml
          sed -i 's/<\/widget>//g' config.xml
          echo '    <preference name="android-targetSdkVersion" value="35" />' >> config.xml
          echo '    <preference name="android-compileSdkVersion" value="35" />' >> config.xml
          echo '</widget>' >> config.xml
          sed -i 's/"latest"/"*"/g' package.json
          sed -i 's/spec="latest"/spec="*"/g' config.xml

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app_project/shadows.keystore

      - name: Create build.json
        run: |
          cat <<EOF > app_project/build.json
          {
            "android": {
              "release": {
                "keystore": "shadows.keystore",
                "storePassword": "${{ secrets.KEYSTORE_PASSWORD }}",
                "alias": "${{ secrets.KEY_ALIAS }}",
                "password": "${{ secrets.KEY_PASSWORD }}",
                "keystoreType": ""
              }
            }
          }
          EOF

      - name: Install Cordova & Build
        run: |
          npm install -g cordova
          cd app_project
          cordova plugin add cordova-plugin-androidx-adapter --save
          npm install
          cordova platform add android@13.0.0
          cordova build android --release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shadows-android-release-signed
          path: |
            app_project/platforms/android/app/build/outputs/bundle/release/*.aab
